# Generated by Django 4.1 on 2022-08-04 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=120)),
                ('username', models.CharField(max_length=120)),
                ('rasm', models.URLField(blank=True)),
                ('bio', models.CharField(blank=True, max_length=500)),
                ('public', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Xabar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.CharField(max_length=500)),
                ('vaqt', models.DateTimeField(auto_now_add=True)),
                ('jonatuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xabar_jonatuvchi', to='app1.profil')),
                ('qabul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xabar_qabulqiluvchi', to='app1.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Reaksiya_xabar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaksiya', models.CharField(max_length=500)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.profil')),
                ('xabar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.xabar')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField()),
                ('vaqt', models.DateTimeField(auto_now_add=True)),
                ('joy', models.CharField(max_length=120)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fayl', models.URLField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.post')),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='app1.profil')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='app1.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.CharField(max_length=500)),
                ('sana', models.DateField(auto_now_add=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.post')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.profil')),
            ],
            options={
                'unique_together': {('profil', 'post_id')},
            },
        ),
        migrations.CreateModel(
            name='Comment_like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.comment')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.profil')),
            ],
            options={
                'unique_together': {('comment', 'profil')},
            },
        ),
    ]
